@file:OptIn(kotlinx.cinterop.ExperimentalForeignApi::class, kotlinx.cinterop.BetaInteropApi::class)

package pt.hitv.feature.player

import platform.Foundation.NSNumber
import platform.UIKit.UIDevice

/**
 * Force-rotates the app between portrait and landscape, mirroring the rotate
 * button in the Android player.
 *
 * Implementation notes / why this code looks like it does:
 * - Uses the KVC-on-`UIDevice` form (`setValue:forKey:` with `"orientation"`).
 *   Technically a private API but it's the only single-call rotation approach
 *   that works on iOS 13–17 from a non-SwiftUI context. The proper iOS 16+
 *   replacement (`UIWindowScene.requestGeometryUpdate(.iOS(...))`) needs
 *   `UIWindowSceneGeometryPreferencesIOS` — not exposed in our cinterop.
 * - We DON'T read `UIDevice.currentDevice.orientation` to decide what to flip
 *   to, because `UIDeviceOrientation` is an enum class in cinterop whose
 *   top-level value constants (`UIDeviceOrientationLandscapeLeft` etc.) aren't
 *   re-exported as imports in this Kotlin/Native version. Tracking the last
 *   value we requested ourselves is good enough for a button toggle.
 * - `NSNumber.numberWithLong` is the Long-typed factory; `numberWithInt`
 *   isn't generated by cinterop on top of `+ (NSNumber*)numberWithInteger:`.
 *
 * Info.plist declares portrait + landscapeLeft + landscapeRight in
 * `UISupportedInterfaceOrientations`, so the system honors the request.
 *
 * UIInterfaceOrientation values (NSInteger):
 *   1 = portrait, 3 = landscapeRight, 4 = landscapeLeft.
 */

// 1 = UIInterfaceOrientationPortrait. First tap flips to landscape.
private var lastRequestedOrientation: Long = 1L

internal fun toggleDeviceOrientation() {
    val next: Long = if (lastRequestedOrientation == 1L) 3L else 1L
    lastRequestedOrientation = next
    UIDevice.currentDevice.setValue(NSNumber.numberWithLong(next), forKey = "orientation")
}
