package pt.hitv.core.model.movieInfo

data class Video(
    val index: Int,
    val codecName: String,
    val codecLongName: String,
    val profile: String,
    val codecType: String,
    val codecTimeBase: String,
    val codecTagString: String,
    val codecTag: String,
    val width: Int,
    val height: Int,
    val codedWidth: Int,
    val codedHeight: Int,
    val hasBFrames: Int,
    val sampleAspectRatio: String,
    val displayAspectRatio: String,
    val pixFmt: String,
    val level: Int,
    val chromaLocation: String,
    val refs: Int,
    val isAvc: Boolean,
    val nalLengthSize: Int,
    val rFrameRate: String,
    val avgFrameRate: String,
    val timeBase: String,
    val startPts: Int,
    val startTime: Double,
    val durationTs: Int,
    val duration: Double,
    val bitRate: Int,
    val bitsPerRawSample: Int,
    val nbFrames: Int,
    val disposition: Disposition,
    val tags: Tags
)
